<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Adminhtml\Transparent\Form $block
 */
$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>" style="display:none;">
    <div class="field-type admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_type">
            <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_cc_type" name="payment[cc_type]"
                    class="required-entry validate-cc-type-select admin__control-select">
                <option value=""></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName) : ?>
                    <option value="<?= $block->escapeHtmlAttr($typeCode) ?>" <?php if ($typeCode == $ccType) : ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($typeName) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="field-number admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_number">
            <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?= /* @noEscape */ $code ?>_cc_number" name="payment[cc_number]" maxlength="19" 
                   title="<?= $block->escapeHtmlAttr(__('Credit Card Number')) ?>" class="admin__control-text validate-cc-number"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_number') ?>"/>
        </div>
    </div>
    <div class="field-date admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_expiration">
            <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_expiration" name="payment[cc_exp_month]"
                    class="admin__control-select admin__control-select-month validate-cc-exp required-entry">
                <?php foreach ($block->getCcMonths() as $k => $v) : ?>
                    <option value="<?= $block->escapeHtmlAttr($k) ?>"
                            <?php if ($k == $ccExpMonth) : ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?= /* @noEscape */ $code ?>_expiration_yr" name="payment[cc_exp_year]"
                    class="admin__control-select admin__control-select-year required-entry">
                <?php foreach ($block->getCcYears() as $k => $v) : ?>
                    <option value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
                            <?php if ($k == $ccExpYear) : ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <?php if ($block->hasVerification()) : ?>
        <div class="field-number required admin__field _required">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_cid">
                <span><?= $block->escapeHtml(__('Card Verification Number')) ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtmlAttr(__('Card Verification Number')) ?>"
                       class="required-entry validate-cc-cvn admin__control-cvn admin__control-text"
                       id="<?= /* @noEscape */ $code ?>_cc_cid"
                       name="payment[cc_cid]" value="<?= /* @noEscape */ $block->getInfoData('cc_cid') ?>"/>
            </div>
        </div>
    <?php endif; ?>
	<?php if ($block->hasAVSZip()): ?>
	<div class="required admin__field _required avs-zipcode">
		<label for="<?= /* @noEscape */ $code ?>_avs_zipcode" class="admin__field-label">
			<span><?= $block->escapeHtml(__('Zip Code')) ?></span>
		</label>
		<div class="admin__field-control">
			<input type="text" name="payment[avs_zipcode]" title="<?= $block->escapeHtml(__('Zip Code')) ?>" class="required-entry admin__control-text" 
			id="<?= /* @noEscape */ $code ?>_avs_zipcode" value="<?= /* @noEscape */ $block->getInfoData('avs_zipcode') ?>" />
		</div>
	</div>
	<?php endif; ?>

	<?php if ($block->hasAVSAddress()): ?>
	<div class="required admin__field _required avs-address">
		<label for="<?= /* @noEscape */ $code ?>_avs_zipcode" class="admin__field-label">
			<span><?= $block->escapeHtml(__('Address')) ?></span>
		</label>
		<div class="admin__field-control">
			<input type="text" name="payment[avs_address]" title="<?= $block->escapeHtml(__('Address')) ?>" class="required-entry admin__control-text" 
			id="<?= /* @noEscape */ $code ?>_avs_address" value="<?= /* @noEscape */ $block->getInfoData('avs_address') ?>" />
		</div>
	</div>
	<?php endif; ?>
</fieldset>
<script>
jQuery(document).ready(function() {
    jQuery("#order-billing_address_street0").change(function(){
      
      	jQuery("#valorpay_gateway_avs_address").val( jQuery("#order-billing_address_street0").val() );
      	
    });
    jQuery("#order-billing_address_postcode").change(function(){
    	
    	jQuery("#valorpay_gateway_avs_zipcode").val( jQuery("#order-billing_address_postcode").val() );
      	
    });
    
    setTimeout(function() {
    	jQuery("#valorpay_gateway_avs_address").val( jQuery("#order-billing_address_street0").val() );
    	jQuery("#valorpay_gateway_avs_zipcode").val( jQuery("#order-billing_address_postcode").val() );
    },2000);
    
    jQuery("input").each(function() {
    	if( jQuery(this).attr('name') == 'payment[method]' ) {
		jQuery(this).on('change',function(){
			jQuery('order-shipping-method-info').hide();
			jQuery('order-shipping-method-choose').show();
			order.setShippingMethod(null);
    		});
    	}
    });
});
</script>