<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Transparent\Form $block
 */
$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
?>
<fieldset class="fieldset payment items ccard <?= /* @noEscape */ $code ?>"
          id="payment_form_<?= /* @noEscape */ $code ?>">

    <?php if ($block->getShowCards()): ?>  
        <input type="hidden" name="payment[cc_id]" id="<?= /* @noEscape */ $code ?>_cc_id" value="" />    
        <div class="field card_list required">
            <label for="<?= /* @noEscape */ $code ?>_payment_informations" class="label">
                <span><?= $block->escapeHtmlAttr(__('Payment Informations')) ?></span>
            </label>
            <div class="control">
                <select id="<?= /* @noEscape */ $code ?>_payment_informations"
                        name="payment[cards]" data-validate='{
                            required:true
                        }'
                        class="select">
                    <option value=""><?= $block->escapeHtml(__('--Please Select--')) ?></option>
                <?php foreach ($block->getStoredCards() as $cards => $card): ?>
                    <option value="<?= $block->escapeHtmlAttr($card->getCcType()) ?>">
                        <?= $block->escapeHtmlAttr($card->getCcType()." ending in ".$card->getCcLast4()." (".$card->getCcName().")") ?>
                    </option>
                <?php endforeach; ?>
                <option value="-1"><?= $block->escapeHtmlAttr(__('New Card')) ?></option>
                </select>
            </div>
        </div>      
    <?php endif; ?>
          
    <div class="field type required hide-if-cards-available">
        <label for="<?= /* @noEscape */ $code ?>_cc_type" class="label">
            <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
        </label>
        <div class="control">
            <select id="<?= /* @noEscape */ $code ?>_cc_type"
                    data-mage-init='{
                        "creditCardType":{"creditCardTypeContainer":"#<?= /* @noEscape */ $code ?>_cc_type_ss_div"}
                    }'
                    name="payment[cc_type]" data-validate='{
                        required:true,
                        "validate-cc-type-select":"#<?= /* @noEscape */ $code ?>_cc_number"
                    }'
                    class="select">
                <option value=""><?= $block->escapeHtml(__('--Please Select--')) ?></option>
            <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                <option value="<?= $block->escapeHtmlAttr($typeCode) ?>"
                    <?php if ($typeCode == $ccType): ?> selected="selected"<?php endif; ?>>
                    <?= $block->escapeHtml($typeName) ?>
                </option>
            <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="field number required hide-if-cards-available">
        <label for="<?= /* @noEscape */ $code ?>_cc_number" class="label">
            <span><?= $block->escapeHtmlAttr(__('Credit Card Number')) ?></span>
        </label>
        <div class="control">
            <input type="number" id="<?= /* @noEscape */ $code ?>_cc_number" name="payment[cc_number]"
                   title="<?= $block->escapeHtml(__('Credit Card Number')) ?>"  onKeyDown="if(this.value.length==19 && event.keyCode!=8) return false;" class="input-text" value=""
                   data-validate='{
                       "required-number":true,
                       "validate-cc-number":"#<?= /* @noEscape */ $code ?>_cc_type",
                       "validate-cc-type":"#<?= /* @noEscape */ $code ?>_cc_type"
                   }'/>
        </div>
    </div>
    <div class="field date required hide-if-cards-available" id="<?= /* @noEscape */ $code ?>_cc_type_exp_div">
        <label for="<?= /* @noEscape */ $code ?>_expiration" class="label">
            <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="control">
            <div class="fields group group-2">
                <div class="field no-label month">
                    <div class="control">
                        <select id="<?= /* @noEscape */ $code ?>_expiration"
                                name="payment[cc_exp_month]"
                                class="select month"
                                data-validate='{required:true, "validate-cc-exp":"#<?= /* @noEscape */ $code
                                ?>_expiration_yr"}'>
                            <?php foreach ($block->getCcMonths() as $k => $v): ?>
                                <option value="<?= /* @noEscape */ $k ? $block->escapeHtmlAttr($k) : '' ?>"
                                    <?php if ($k == $ccExpMonth): ?> selected="selected"<?php endif; ?>>
                                    <?= $block->escapeHtml($v) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                <div class="field no-label year">
                    <div class="control">
                        <select id="<?= /* @noEscape */ $code ?>_expiration_yr" name="payment[cc_exp_year]"
                                class="select year" data-validate='{required:true}'>
                            <?php foreach ($block->getCcYears() as $k => $v): ?>
                                <option value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>
                                "<?php if ($k == $ccExpYear): ?> selected="selected"<?php endif; ?>>
                                    <?= $block->escapeHtml($v) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php if ($block->hasVerification()): ?>
    <div class="field cvv required hide-if-cards-available" id="<?= /* @noEscape */ $code ?>_cc_type_cvv_div">
        <label for="<?= /* @noEscape */ $code ?>_cc_cid" class="label">
            <span><?= $block->escapeHtmlAttr(__('Card Verification Number')) ?></span>
        </label>
        <div class="control">
            <input type="number" onKeyDown="if(this.value.length==4 && event.keyCode!=8) return false;" title="<?= $block->escapeHtml(__('Card Verification Number')) ?>"
                   class="input-text cvv" id="<?= /* @noEscape */ $code ?>_cc_cid" name="payment[cc_cid]" value=""
                   data-validate='{"required-number":true, "validate-cc-cvn":"#<?= /* @noEscape */ $code ?>_cc_type"}'/>
            <?php $content = '<img src=\"' . $block->getViewFileUrl('Magento_Checkout::cvv.png') . '\" alt=\"' .
                $block->escapeHtml(__('Card Verification Number Visual Reference')) .
                '\" title=\"' . $block->escapeHtml(__('Card Verification Number Visual Reference')) . '\" />'; ?>
            <div class="note">
                <a href="#" class="action cvv" title="<?= $block->escapeHtml(__('What is this?')) ?>"
                   data-mage-init='{"tooltip": {"content": "<?= /* @noEscape */ $content ?>"}}'>
                    <span><?= $block->escapeHtml(__('What is this?')) ?></span>
                </a>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <?php if ($block->getShowSaveCard()): ?>
        <div class="field hide-if-cards-available">
            <div class="control">
                <input type="checkbox" name="payment[save]" class="checkbox" id="<?php /* @noEscape */ echo $code; ?>_save" value="1" />
                <label class="label" for="<?php /* @noEscape */ echo $code; ?>_save">
                    <span><?= $block->escapeHtmlAttr(__('Save for next time')) ?></span>
                </label>
            </div>
        </div>
    <?php endif; ?>

    <div class="field">
        <div class="control">
            <input type="checkbox" name="payment[terms_checked]" class="checkbox" id="<?php /* @noEscape */ echo $code; ?>_terms_checked" value="1" checked/><label
                class="label" for="<?php /* @noEscape */ echo $code; ?>_terms_checked">
                <span><?= $block->escapeHtml(__('I agree to the')) ?> <a href="https://valorpaytech.com/privacy-policy/" target="_blank"><?= $block->escapeHtml(__('Terms And Conditions')) ?></a></span></label>
        </div>
    </div>
    
    <?= $block->getChildHtml() ?>
</fieldset>
<script type="text/javascript">
    require(['jquery', 'vaultscript'], function($, selectCard) {

        $(document).ready(function(){
            selectCard();
        });
    });
</script>